"""add hashed_password to user model

Revision ID: a7618f996278
Revises: 5eff402e3746
Create Date: 2025-05-25 20:05:14.200671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7618f996278'
down_revision = '5eff402e3746'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_sync_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metrics_synced', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['data_source_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('withings_measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['data_source_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withings_measurements_connection_id'), 'withings_measurements', ['connection_id'], unique=False)
    op.create_index('ix_withings_measurements_connection_id_type_timestamp', 'withings_measurements', ['connection_id', 'type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_withings_measurements_timestamp'), 'withings_measurements', ['timestamp'], unique=False)
    op.create_index(op.f('ix_withings_measurements_type'), 'withings_measurements', ['type'], unique=False)
    op.add_column('health_metrics', sa.Column('meta', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    op.drop_column('health_metrics', 'meta')
    op.drop_index(op.f('ix_withings_measurements_type'), table_name='withings_measurements')
    op.drop_index(op.f('ix_withings_measurements_timestamp'), table_name='withings_measurements')
    op.drop_index('ix_withings_measurements_connection_id_type_timestamp', table_name='withings_measurements')
    op.drop_index(op.f('ix_withings_measurements_connection_id'), table_name='withings_measurements')
    op.drop_table('withings_measurements')
    op.drop_table('data_sync_logs')
    op.drop_table('data_source_connections')
    # ### end Alembic commands ### 